In [56]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("dataset/complate_data.csv")

In [5]:
data.head()

Unnamed: 0  Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0           0   0            5.1           3.5            1.4           0.2   
1           1   1            4.7           3.2            1.6           0.2   
2           3   3            4.4           2.9            1.4           0.2   
3           4   4            5.0           3.4            1.5           0.2   
4           5   5            4.6           3.4            1.4           0.3   

       Species  
0  Iris-setosa  
1  Iris-setosa  
2  Iris-setosa  
3  Iris-setosa  
4  Iris-setosa

In [10]:
data.drop(["Unnamed: 0", "Id"], axis=1, inplace=True)

In [11]:
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.7           3.2            1.6           0.2  Iris-setosa
2            4.4           2.9            1.4           0.2  Iris-setosa
3            5.0           3.4            1.5           0.2  Iris-setosa
4            4.6           3.4            1.4           0.3  Iris-setosa

## Label Encoding


In [13]:
le=LabelEncoder()

In [14]:
data["Species"] = le.fit_transform(data["Species"])

In [15]:
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.7           3.2            1.6           0.2        0
2            4.4           2.9            1.4           0.2        0
3            5.0           3.4            1.5           0.2        0
4            4.6           3.4            1.4           0.3        0

## Conrtols on Data

In [17]:
data.isna().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [19]:
data.dtypes

SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species            int32
dtype: object

In [20]:
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.7           3.2            1.6           0.2        0
2            4.4           2.9            1.4           0.2        0
3            5.0           3.4            1.5           0.2        0
4            4.6           3.4            1.4           0.3        0

## Train_test_Split

In [21]:
from sklearn.model_selection import train_test_split

In [39]:
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:, :-1], data.iloc[:,-1], test_size=0.2)

In [40]:
y_train.value_counts()

1    42
2    41
0    27
Name: Species, dtype: int64

In [41]:
y_test.value_counts()

2    13
1    11
0     4
Name: Species, dtype: int64

## Creating Model

In [43]:
import xgboost as xgb

In [48]:
xgb_cls = xgb.XGBClassifier(objective="multiclass:softmax", num_class= 3)

In [52]:
xgb_cls.fit(X_train, y_train )

[22:06:50] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\sukru\anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=12, num_class=3, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [53]:
X_test

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
41             6.9           3.1            4.9           1.5
108            7.9           3.8            6.4           2.0
107            7.7           2.6            6.9           2.3
127            7.7           3.8            6.7           2.2
69             5.7           3.0            4.2           1.2
99             6.1           3.0            4.9           1.8
52             6.1           2.8            4.0           1.3
103            7.7           2.8            6.7           2.0
57             5.2           2.7            3.9           1.4
4              4.6           3.4            1.4           0.3
1              4.7           3.2            1.6           0.2
109            6.7           2.5            5.8           1.8
42             5.7           2.6            3.5           1.0
75             5.4           3.0            4.5           1.5
90             6.3           2.9            5.6           1.8
59             5.9           3.0            4.2           1.5
15             5.2           3.4            1.4           0.2
71             6.1           3.0            4.6           1.4
93             5.8           2.7            5.1           1.9
85             6.4           3.2            5.3           2.3
115            6.0           3.0            4.8           1.8
66             5.5           2.6            4.4           1.2
84             7.3           2.9            6.3           1.8
22             4.4           3.2            1.3           0.2
87             6.3           2.8            5.1           1.5
32             6.7           3.1            4.4           1.4
46             6.8           2.8            4.8           1.4
131            7.2           3.2            6.0           1.8

In [54]:
preds = xgb_cls.predict(X_test)

In [55]:
preds

array([1, 2, 2, 2, 1, 2, 1, 2, 1, 0, 0, 2, 1, 1, 2, 1, 0, 1, 2, 2, 1, 1,
       2, 0, 2, 1, 1, 2])

In [57]:
np.array(y_test)

array([1, 2, 2, 2, 1, 2, 1, 2, 1, 0, 0, 2, 1, 1, 2, 1, 0, 1, 2, 2, 2, 1,
       2, 0, 2, 1, 1, 2])

In [58]:
from sklearn.metrics import accuracy_score, confusion_matrix


In [60]:
accuracy_score(y_test, preds)

0.9642857142857143

## accuracy_score : %96

In [61]:
confusion_matrix(y_test,preds)

array([[ 4,  0,  0],
       [ 0, 11,  0],
       [ 0,  1, 12]], dtype=int64)